# Cart routes
cart_index:
    path: /cart
    controller: App\Controllers\CartController::index
    methods: GET

cart_order:
    path: /cart/order
    controller: App\Controllers\OrderController::preview
    methods: POST

cart_store:
    path: /cart/{id}
    controller: App\Controllers\CartController::store
    methods: POST

cart_destroy:
    path: /cart/{id}
    controller: App\Controllers\CartController::destroy
    methods: DELETE

# Product routes
product_index:
    path: /products
    controller: App\Controllers\ProductController::index
    methods: GET

product_index_1:
    path: /
    controller: App\Controllers\ProductController::index
    methods: GET

product_create:
    path: /products/create
    controller: App\Controllers\ProductController::create
    methods: GET

product_show:
    path: /products/{id}
    controller: App\Controllers\ProductController::show
    methods: GET

product_store:
    path: /products
    controller: App\Controllers\ProductController::store
    methods: POST

product_edit:
    path: /products/edit/{id}
    controller: App\Controllers\ProductController::edit
    methods: GET

product_update:
    path: /products/{id}
    controller: App\Controllers\ProductController::update
    methods: POST

product_destroy:
    path: /products/{id}
    controller: App\Controllers\ProductController::destroy
    methods: DELETE

# Register routes
user_create:
    path: /register
    controller: App\Controllers\RegisterController::index
    methods: GET

user_store:
    path: /register
    controller: App\Controllers\RegisterController::store
    methods: POST

# Login routes
login_index:
    path: /login
    controller: App\Controllers\LoginController::index
    methods: GET

login_check:
    path: /login
    controller: App\Controllers\LoginController::store
    methods: POST

# Logout routes
logout_index:
    path: /logout
    controller: App\Controllers\LogoutController::index
    methods: GET

# Search routes
search_index:
    path: /search
    controller: App\Controllers\SearchController::index

# Admin routes
admin_index:
    path: /admin
    controller: App\Controllers\AdminController::index

admin_product_index:
    path: /admin/products
    controller: App\Controllers\AdminProductController::index

admin_order_index:
    path: /admin/orders
    controller: App\Controllers\AdminOrderController::index

# Order routes
order_index:
    path: /orders
    controller: App\Controllers\OrderController::index
    methods: GET

order_store:
    path: /orders
    controller: App\Controllers\OrderController::store
    methods: POST

order_destroy:
    path: /orders/{id}
    controller: App\Controllers\OrderController::destroy
    methods: DELETE

order_show:
    path: /orders/{id}
    controller: App\Controllers\OrderController::show
    methods: GET

# Profile routes
profile_edit:
    path: /user
    controller: App\Controllers\ProfileController::edit
    methods: GET

profile_update:
    path: /user
    controller: App\Controllers\ProfileController::update
    methods: PUT