product_index:
    path: /product
    controller: App\Controllers\ProductController::index

product_show:
    path: /product/{id}
    controller: App\Controllers\ProductController::show

cart_index:
    path: /cart
    controller: App\Controllers\CartController::index

auth_index:
    path: /auth
    controller: App\Controllers\AuthController::index

search:
    path: /search
    controller: App\Controllers\SearchController::search